#!/bin/sh
eval "$(/usr/bin/garden-exec)" 
set -e

NAME=viparr
DESCRIPTION="Builds forcefields"

SCONS=scons/3.1.2-01c7
GCC=gcc/6.3.0-01c7
PYTHON=desres-python/3.7.2-08c7
SCONSUTILS=sconsutils/1.51c7

loadmodules() {
    garden load `cat $(dirname $0)/modules.txt`
    MSYS=msys/$(echo $(basename $MSYS_PREFIX) | awk -F_ '{print $1}')
    garden load \
        $SCONS/bin \
        $MSYS/lib \
        $PYTHON/bin \
        $GCC/bin \
        $MSYS/lib-python37 \
        $SCONSUTILS/lib-python37 \

   export PYTHONVER=37
}

genmodules() {
    cat << EOF > $GARDENDIR/lib-python37
prepend-path PYTHONPATH ${PREFIX}/lib/python
EOF

    cat << EOF > $GARDENDIR/bin
prepend-path PATH $PREFIX/bin
EOF

    # library
    cat << EOF > $GARDENDIR/lib
prereq $MSYS/lib
prepend-path DESRES_MODULE_CPPFLAGS -I$PREFIX/include
prepend-path DESRES_MODULE_LDFLAGS -L$PREFIX/lib 
prepend-path DESRES_MODULE_LDFLAGS -Wl,-rpath,$PREFIX/lib
EOF
}

runtests() {
    loadmodules
    PYTHONPATH=${PREFIX:-build}/lib/python:$PYTHONPATH python3 test/python_tests.py "$@"
    ./test/run.sh -v
}

genhelp() {
    cat doc/source/release_notes.txt
}

case $1 in
    --name)
        echo $NAME
        ;;
    --version)
        echo `src/version.py`c7
        ;;
    --exec)
        shift
	loadmodules
        "$@"
        ;;
    --install)
	loadmodules
        nprocs=`nproc`
        $0 --exec scons -j$nprocs install PREFIX=${PREFIX} OBJDIR=$TMPDIR

        runtests
        $PREFIX/bin/viparr -h > /dev/null
        $PREFIX/bin/viparr_neutralize -h > /dev/null
        $PREFIX/bin/viparr_solvate -h > /dev/null
        $PREFIX/bin/viparr-make-rigid -h > /dev/null
        (cd doc && PYTHONPATH=$PREFIX/lib/python:$PYTHONPATH make clean html)

        mkdir -p $PREFIX/doc
        cp -r doc/build/* $PREFIX/doc
	genmodules
        genhelp > $METADIR/help.txt
        ;;
    # It's not an error if nothing matches.  desres-install may invent
    # other arguments in the future.
esac

