Import('env')

env.Append(CPPPATH=['../src'], LIBS=['viparr'], CXXFLAGS=["-fvisibility=hidden"])
if True:
    env.Append(CXXFLAGS=["-flto"], LINKFAGS=["-flto"])

env.AddPythonExtension('_viparr', "viparr.cxx", prefix='viparr')
env.AddPythonModule('__init__.py', prefix='viparr')
